# Generated by Django 5.1.6 on 2025-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentorderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorderitem',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
