# Generated by Django 5.1.6 on 2025-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentorderitem_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorderitem',
            name='return_approved',
            field=models.BooleanField(default=False),
        ),
    ]
