# Generated by Django 5.1.6 on 2025-03-13 06:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/category/')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_initial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/product/')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('rating', models.DecimalField(decimal_places=1, default=3, max_digits=2)),
                ('is_blocked', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(default=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default='plastic', max_length=50, null=True)),
                ('connectivity', models.CharField(blank=True, default='wired connection', max_length=50, null=True)),
                ('led_indicators', models.CharField(blank=True, default='led for battery level', max_length=50, null=True)),
                ('portabilty', models.CharField(blank=True, default='easy to carry', max_length=50, null=True)),
                ('os_support', models.CharField(blank=True, default='Compatible with android,Linux,Windows,etc', max_length=50, null=True)),
                ('touch_countrols', models.CharField(blank=True, default='Advanced controls using touch screen integration', max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.product')),
            ],
        ),
    ]
