# Generated by Django 5.1.6 on 2025-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_product_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
