# Generated by Django 5.1.6 on 2025-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_base_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_initial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
