# Generated by Django 5.1.6 on 2025-03-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_usedreferral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedreferral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='usedreferral',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferralCodeSystem',
        ),
        migrations.DeleteModel(
            name='UsedReferral',
        ),
    ]
