# Generated by Django 5.1.6 on 2025-03-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('myapp', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
