# Generated by Django 5.1.6 on 2025-03-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_items_product_variant_alter_cart_items_product'),
        ('myapp', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_variant_items', to='myapp.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'product_variant')},
        ),
    ]
