# Generated by Django 5.1.6 on 2025-03-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_wishlistitem_unique_together_and_more'),
        ('myapp', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='myapp.product'),
        ),
    ]
